// generated from tallytaylor.com

export const retailProducts = [
  { id: "t5749w", style: "T5749W", name: "Plus Size Floral Puff Sleeve Jacket & Midi Skirt Set", price: 159.5, color: "DEEP EMERALD", sizes: ["Misses"], image: "/images/products/t5749w.png" },
  { id: "t5749", style: "T5749", name: "Floral Puff Sleeve Jacket & Midi Skirt Set", price: 159.5, color: "DEEP EMERALD", sizes: ["Misses"], image: "/images/products/t5749.jpg" },
  { id: "5401", style: "5401", name: "Jeweled Detail Knit Skirt Suit", price: 359.5, color: "BLACK | ROYAL", sizes: ["Misses"], image: "/images/products/5401.jpg" },
  { id: "s0276w", style: "S0276W", name: "Pleated Statement Plus Size Midi Dress", price: 99.5, color: "GOLD", sizes: ["Misses"], image: "/images/products/s0276w.png" },
  { id: "s0276", style: "S0276", name: "Pleated Statement Midi Dress", price: 99.5, color: "GOLD", sizes: ["Misses"], image: "/images/products/s0276.jpg" },
  { id: "41149", style: "41149", name: "Denim Floral Print Puff Sleeve Maxi Dress", price: 179.5, color: "DENIM BLUE", sizes: ["Misses"], image: "/images/products/41149.jpg" },
  { id: "41038", style: "41038", name: "Marbella Printed Maxi Dress", price: 159.5, color: "RED MULTI", sizes: ["Misses"], image: "/images/products/41038.jpg" },
  { id: "9879", style: "9879", name: "Satin Maxi Dress with Printed Trim", price: 139.5, color: "BROWN MULTI", sizes: ["Misses"], image: "/images/products/9879.jpg" },
  { id: "41093w", style: "41093W", name: "Plus Size Embroidered Clergy Midi Dress", price: 179.5, color: "WHITE/GOLD", sizes: ["Misses"], image: "/images/products/41093w.png" },
  { id: "41093", style: "41093", name: "Embroidered Clergy Midi Dress", price: 179.5, color: "WHITE/GOLD", sizes: ["Misses"], image: "/images/products/41093.jpg" },
  { id: "u0261w", style: "U0261W", name: "Plus Size Elegant Sequin A-Line Dress", price: 139.5, color: "RED MULTI", sizes: ["Misses"], image: "/images/products/u0261w.png" },
  { id: "u0110", style: "U0110", name: "Jeweled Bow Statement Hat", price: 119.5, color: "RED/GREEN", sizes: ["Misses"], image: "/images/products/u0110.jpg" },
  { id: "s0278w", style: "S0278W", name: "Plus Size High-Low Shirt Dress", price: 99.5, color: "BLACK", sizes: ["Misses"], image: "/images/products/s0278w.png" },
  { id: "s0278", style: "S0278", name: "High-Low Shirt Dress", price: 99.75, color: "BLACK", sizes: ["Misses"], image: "/images/products/s0278.jpg" },
  { id: "s0063w", style: "S0063W", name: "Plus Size Sequin Lace Puff Sleeve Midi Dress", price: 119.5, color: "GREEN", sizes: ["Misses"], image: "/images/products/s0063w.png" },
  { id: "s0063", style: "S0063", name: "Sequin Lace Puff Sleeve Midi Dress", price: 119.5, color: "GREEN", sizes: ["Misses"], image: "/images/products/s0063.jpg" },
  { id: "h5749", style: "H5749", name: "Two-Tone Feather Fascinator Headband", price: 79.5, color: "DEEP EMERALD", sizes: ["Misses"], image: "/images/products/h5749.jpg" },
  { id: "h0617", style: "H0617", name: "Jeweled Bow Church Hat", price: 119.5, color: "PURPLE/GREEN", sizes: ["Misses"], image: "/images/products/h0617.jpg" },
  { id: "s0274w", style: "S0274W", name: "Plus Size Geo Circle Print Long Tunic Pant Set", price: 99.5, color: "OLIVE MULTI", sizes: ["Misses"], image: "/images/products/s0274w.png" },
  { id: "s0274", style: "S0274", name: "Geo Circle Print Long Tunic Pant Set", price: 99.5, color: "OLIVE MULTI", sizes: ["Misses"], image: "/images/products/s0274.webp" },
  { id: "s0272w", style: "S0272W", name: "Plus Size Sequin Sleeve Maxi Dress", price: 99.5, color: "DENIM", sizes: ["Misses"], image: "/images/products/s0272w.png" },
  { id: "s0272", style: "S0272", name: "Sequin Sleeve Maxi Dress", price: 99.5, color: "DENIM", sizes: ["Misses"], image: "/images/products/s0272.jpg" },
  { id: "s0267", style: "S0267", name: "Wavy Graphic Print Tiered Maxi Dress", price: 99.5, color: "BLACK MULTI", sizes: ["Misses"], image: "/images/products/s0267.jpg" },
  { id: "u0617w", style: "U0617W", name: "Plus Size Cape Sheath Dress", price: 119.5, color: "PURPLE/GREEN", sizes: ["Misses"], image: "/images/products/u0617w.png" },
  { id: "u0617", style: "U0617", name: "Cape Sheath Dress", price: 119.5, color: "PURPLE/GREEN", sizes: ["Misses"], image: "/images/products/u0617.webp" },
  { id: "u0109", style: "U0109", name: "Floral Print Jacket & Midi Skirt Set", price: 139.5, color: "RED/GREEN", sizes: ["Misses"], image: "/images/products/u0109.jpg" },
  { id: "u0055w", style: "U0055W", name: "Floral Lace Dress & Satin Jacket Set", price: 179.5, color: "BURNT ORANGE", sizes: ["Misses"], image: "/images/products/u0055w.png" },
  { id: "s0267w", style: "S0267W", name: "Plus Size Wavy Graphic Print Tiered Maxi Dress", price: 99.5, color: "BLACK MULTI", sizes: ["Misses"], image: "/images/products/s0267w.png" },
  { id: "u0527w", style: "U0527W", name: "Plus Size Crystal Trim Chiffon Caftan Dress", price: 89.5, color: "WHITE", sizes: ["Misses"], image: "/images/products/u0527w.png" },
  { id: "u0527", style: "U0527", name: "Crystal Trim Chiffon Caftan Dress", price: 79.5, color: "WHITE", sizes: ["Misses"], image: "/images/products/u0527.jpg" },
  { id: "u0055", style: "U0055", name: "Floral Lace Dress & Satin Jacket Set", price: 179.5, color: "BURNT ORANGE", sizes: ["Misses"], image: "/images/products/u0055.jpg" },
  { id: "9869", style: "9869", name: "Floral Puff Sleeve Sheath Dress", price: 139.5, color: "Twilight Blue", sizes: ["Misses"], image: "/images/products/9869.jpg" },
  { id: "9825", style: "9825", name: "Spring Blossom A-Line Dress", price: 179.5, color: "GREEN/MULTI", sizes: ["Misses"], image: "/images/products/9825.jpg" },
  { id: "4848", style: "4848", name: "Brocade Dress with Bishop Sleeves", price: 179.5, color: "BLACK/WHITE | BURNT ORANGE MULTI | TURQUOISE/GOLD | YELLOW MULTI", sizes: ["Misses"], image: "/images/products/4848.png" },
  { id: "41142w", style: "41142W", name: "Plus Size Regal Trim Women's Clergy Robe", price: 119.5, color: "BLACK | PURPLE | WHITE | WHITE/PURPLE", sizes: ["Misses"], image: "/images/products/41142w.png" },
  { id: "4813", style: "4813", name: "Clergy Dress with Puff Sleeves", price: 119.5, color: "BLACK/WHITE | NAVY | PURPLE/WHITE | ROYAL/WHITE | WHITE/BLACK | SILVER | RED | BURGUNDY", sizes: ["Misses"], image: "/images/products/4813.jpg" },
  { id: "9871", style: "9871", name: "Regal Puff Sleeve Midi Dress", price: 139.5, color: "EMERALD GREEN | WHITE", sizes: ["Misses"], image: "/images/products/9871.png" },
  { id: "7328", style: "7328", name: "Majestic Plum Sparkle Suit", price: 778, color: "DEEP PURPLE", sizes: ["Misses"], image: "/images/products/7328.jpg" },
  { id: "41142", style: "41142", name: "Regal Trim Women's Clergy Robe", price: 119.5, color: "BLACK | PURPLE | WHITE | WHITE/PURPLE", sizes: ["Misses"], image: "/images/products/41142.jpg" },
  { id: "9848", style: "9848", name: "Sculpted Mosaic Sheath Dress", price: 139.5, color: "BLUE/MULTI | PURPLE MULTI", sizes: ["Misses"], image: "/images/products/9848.jpg" },
  { id: "41039", style: "41039", name: "Elegant Dress & Jacket Set with Brooch", price: 199.5, color: "WHITE", sizes: ["Misses"], image: "/images/products/41039.jpg" },
  { id: "41090", style: "41090", name: "Ombre Abstract Print Jacket Dress Set", price: 199.5, color: "YELLOW MULTI", sizes: ["Misses"], image: "/images/products/41090.jpg" },
  { id: "41088", style: "41088", name: "Abstract Print Dress & Duster Set", price: 199.5, color: "PINK MULTI", sizes: ["Misses"], image: "/images/products/41088.jpg" },
  { id: "41095", style: "41095", name: "Brocade Dress with Peplum Jacket Set", price: 199.5, color: "BLUE/MULTI", sizes: ["Misses"], image: "/images/products/41095.jpg" },
  { id: "41086", style: "41086", name: "Polka Dot Stripe Bow Detail Midi Dress", price: 179.5, color: "GREEN/MULTI", sizes: ["Misses"], image: "/images/products/41086.jpg" },
  { id: "41085", style: "41085", name: "Colorblock Bow Detail Midi Dress", price: 179.5, color: "RED/BLACK", sizes: ["Misses"], image: "/images/products/41085.jpg" },
  { id: "5397", style: "5397", name: "Rhinestone Knit Jacket & Skirt Set", price: 339.5, color: "LILAC", sizes: ["Misses"], image: "/images/products/5397.jpg" },
  { id: "51015", style: "51015", name: "Multicolor Stripe Knit Top & Skirt Set", price: 199.5, color: "PINK MULTI", sizes: ["Misses"], image: "/images/products/51015.jpg" },
  { id: "51014", style: "51014", name: "Striped Knit Duster Pant Set", price: 299.5, color: "PURPLE MULTI", sizes: ["Misses"], image: "/images/products/51014.jpg" },
  { id: "9851", style: "9851", name: "Metallic Abstract Peplum Skirt Suit", price: 179.5, color: "ORANGE/NAVY", sizes: ["Misses"], image: "/images/products/9851.jpg" },
  { id: "9850", style: "9850", name: "Floral Jacquard Belted Midi Dress", price: 179.5, color: "PINK MULTI", sizes: ["Misses"], image: "/images/products/9850.jpg" },
  { id: "7327", style: "7327", name: "Pearl Trim Tweed Skirt Suit", price: 798, color: "WHITE", sizes: ["Misses"], image: "/images/products/7327.png" },
  { id: "7325", style: "7325", name: "Green Textured Knit Skirt Suit", price: 778, color: "EMERALD GREEN", sizes: ["Misses"], image: "/images/products/7325.jpg" },
  { id: "9846", style: "9846", name: "Bishop Sleeve Tie-Waist Maxi Dress", price: 159.5, color: "ROYAL/BLUE | WHITE", sizes: ["Misses"], image: "/images/products/9846.jpg" },
  { id: "9845", style: "9845", name: "Puff Sleeve Fit & Flare Occasion Dress", price: 179.5, color: "GREEN/MULTI | PURPLE MULTI | WHITE", sizes: ["Misses"], image: "/images/products/9845.jpg" },
  { id: "7326", style: "7326", name: "Black Rhinestone Knit Jacket & Dress Set", price: 518, color: "BLACK", sizes: ["Misses"], image: "/images/products/7326.jpg" },
  { id: "5396", style: "5396", name: "Rhinestone Knit Jacket & Mermaid Skirt Set", price: 359.5, color: "BROWN | WHITE/MULTI", sizes: ["Misses"], image: "/images/products/5396.jpg" },
  { id: "5395", style: "5395", name: "Embellished Knit Skirt Suit Set", price: 359.5, color: "GOLD/BLACK", sizes: ["Misses"], image: "/images/products/5395.jpg" },
  { id: "51013", style: "51013", name: "Chevron Knit Dress & Pant Set", price: 319.5, color: "ORANGE MULTI", sizes: ["Misses"], image: "/images/products/51013.jpg" },
  { id: "41096", style: "41096", name: "Metallic Jacket Church Dress Set", price: 239.5, color: "GOLD | SILVER", sizes: ["Misses"], image: "/images/products/41096.jpg" },
  { id: "41083w", style: "41083W", name: "Plus Size Rhinestone Trim Cross Clergy Robe", price: 179.5, color: "BLACK | WHITE", sizes: ["Misses"], image: "/images/products/41083w.jpg" },
  { id: "41083", style: "41083", name: "Rhinestone Trim Cross Clergy Robe", price: 179.5, color: "BLACK | WHITE", sizes: ["Misses"], image: "/images/products/41083.jpg" },
  { id: "41099w", style: "41099W", name: "Plus Size Jacquard Panel Clergy Robe", price: 199.5, color: "BLACK | WHITE/PURPLE MULTI", sizes: ["Misses"], image: "/images/products/41099w.png" },
  { id: "41099", style: "41099", name: "Jacquard Panel Clergy Robe", price: 199.5, color: "BLACK | WHITE/PURPLE MULTI", sizes: ["Misses"], image: "/images/products/41099.jpg" },
  { id: "41098w", style: "41098W", name: "Plus Size Contrast Panel Clergy Robe", price: 199.5, color: "ROYAL | WHITE", sizes: ["Misses"], image: "/images/products/41098w.png" },
  { id: "41098", style: "41098", name: "Contrast Panel Clergy Robe Dress", price: 199.5, color: "ROYAL | WHITE", sizes: ["Misses"], image: "/images/products/41098.jpg" },
  { id: "41082w", style: "41082W", name: "Plus Size Geometric Yoke Clergy Robe", price: 179.5, color: "RUBY RED | WHITE", sizes: ["Misses"], image: "/images/products/41082w.jpg" },
  { id: "41082", style: "41082", name: "Geometric Yoke Clergy Robe", price: 179.5, color: "RUBY RED | WHITE", sizes: ["Misses"], image: "/images/products/41082.jpg" },
  { id: "41112w", style: "41112W", name: "Majesty Panel Plus Size Clergy Robe", price: 159.5, color: "BLACK MULTI | PURPLE MULTI", sizes: ["Misses"], image: "/images/products/41112w.png" },
  { id: "41112", style: "41112", name: "Majesty Panel Clergy Robe", price: 159.5, color: "BLACK MULTI | PURPLE MULTI", sizes: ["Misses"], image: "/images/products/41112.jpg" },
  { id: "5394", style: "5394", name: "Trinity Sparkle Knit Skirt Suit", price: 319.5, color: "PURPLE | RED", sizes: ["Misses"], image: "/images/products/5394.jpg" },
  { id: "5393", style: "5393", name: "Elegant Floral Appliqué Skirt Suit Set", price: 319.5, color: "BLACK | WHITE", sizes: ["Misses"], image: "/images/products/5393.jpg" },
  { id: "41075", style: "41075", name: "Orchid Maze Jacket & Mermaid Skirt Suit", price: 179.5, color: "PURPLE MULTI", sizes: ["Misses"], image: "/images/products/41075.jpg" },
  { id: "41071w", style: "41071W", name: "Plus size Two-Piece Brocade Clergy Robe", price: 199.5, color: "BLACK MULTI | PURPLE MULTI | WHITE/MULTI", sizes: ["Misses"], image: "/images/products/41071w.png" },
  { id: "41072", style: "41072", name: "Embroidered Sequin Tweed Jacket & Skirt Set", price: 279.5, color: "BLUSH", sizes: ["Misses"], image: "/images/products/41072.jpg" },
  { id: "5388", style: "5388", name: "Glimmer Sheath Dress", price: 319.5, color: "BLACK | EMERALD GREEN", sizes: ["Misses"], image: "/images/products/5388.jpg" },
  { id: "5312w", style: "5312W", name: "Camille Trim Knit Jacket Dress – Plus Size", price: 299.5, color: "BLACK/WHITE", sizes: ["Misses"], image: "/images/products/5312w.jpg" },
  { id: "5312", style: "5312", name: "Camille Trim Knit Jacket Dress", price: 299.5, color: "BLACK/WHITE", sizes: ["Misses"], image: "/images/products/5312.jpg" },
  { id: "41032w", style: "41032W", name: "Elegant Plus Size Tweed Robe", price: 179.5, color: "WHITE | PURPLE", sizes: ["Misses"], image: "/images/products/41032w.jpg" },
  { id: "41032", style: "41032", name: "Elegant Charm Tweed Church Robe", price: 179.5, color: "WHITE | PURPLE", sizes: ["Misses"], image: "/images/products/41032.jpg" },
  { id: "41033w", style: "41033W", name: "Plus Size Plaid Long Jacket Church Dress Set", price: 179.5, color: "BLACK MULTI", sizes: ["Misses"], image: "/images/products/41033w.png" },
  { id: "41033", style: "41033", name: "Plaid Long Jacket Church Dress Set", price: 179.5, color: "BLACK MULTI", sizes: ["Misses"], image: "/images/products/41033.png" },
  { id: "41031w", style: "41031W", name: "Plus Size Velvet Church Robe with Crystal Trim", price: 159.5, color: "BLACK | ROYAL", sizes: ["Misses"], image: "/images/products/41031w.jpg" },
  { id: "41031", style: "41031", name: "Velvet Church Robe with Crystal Trim", price: 159.5, color: "BLACK | ROYAL", sizes: ["Misses"], image: "/images/products/41031.jpg" },
  { id: "5378", style: "5378", name: "Black Sparkle Ruffle Hem Knit Suit", price: 339.5, color: "BLACK MULTI", sizes: ["Misses"], image: "/images/products/5378.jpg" },
  { id: "5374", style: "5374", name: "Black Knit Studded Dress with Ruffle Hem", price: 259.5, color: "BLACK MULTI", sizes: ["Misses"], image: "/images/products/5374.jpg" },
  { id: "4892", style: "4892", name: "Elegant Lace Peplum Suit", price: 199.5, color: "PEACH MULTI | WHITE", sizes: ["Misses"], image: "/images/products/4892.jpg" },
  { id: "5345", style: "5345", name: "Floral Rhinestone Knit Skirt Set", price: 299.5, color: "BURGUNDY | BLACK/SILVER", sizes: ["Misses"], image: "/images/products/5345.jpg" },
  { id: "7312", style: "7312", name: "Liorah Knit Crystal Wave Skirt", price: 878, color: "RED", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7312.jpg" },
  { id: "7302", style: "7302", name: "Shimmer Knit Suit", price: 778, color: "ROYAL | PURPLE | ROSE", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7302.jpg" },
  { id: "7317", style: "7317", name: "Ivory/Gold Floral Embroidered 2-Piece Dress Suit w/ Scalloped Trim", price: 778, color: "IVORY/GOLD", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7317.jpg" },
  { id: "7311", style: "7311", name: "Rose Pink Knit Suit with Floral Trim", price: 798, color: "FUCHSIA", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7311.jpg" },
  { id: "7308", style: "7308", name: "Starlight Ombré Feather Trim Suit", price: 898, color: "BLACK/SILVER", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7308.png" },
  { id: "7319", style: "7319", name: "Peach Textured Knit 2-Piece Midi Suit w/ Button Front Jacket", price: 678, color: "PEACH", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7319.jpg" },
  { id: "7313", style: "7313", name: "Navy & Silver Starburst Skirt Suit", price: 738, color: "NAVY", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7313.jpg" },
  { id: "7304", style: "7304", name: "Silver Shimmer Textured Knit Suit", price: 778, color: "SILVER", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7304.jpg" },
  { id: "7303", style: "7303", name: "Royal Blue Crystal Wave Suit", price: 738, color: "ROYAL", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7303.jpg" },
  { id: "7300", style: "7300", name: "Rose Pink Crystal Shimmer Suit", price: 778, color: "FUCHSIA", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7300.jpg" },
  { id: "7253", style: "7253", name: "Black & White Crystal Contrast Suit", price: 658, color: "BLACK/WHITE", sizes: ["Misses"], tag: "Liorah Knit", image: "/images/products/7253.jpg" },
];

export const wholesaleProducts = [];
